
spring:

    datasource:
        url: jdbc:mysql://localhost:3306/bpms_db
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: _9L#2*6n
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
minio:
    bucket: documents
    url: http://192.168.0.4:9000
    accessKey: minioadmin
    secretKey: minioadmin

